### ISSUE TITLE
Error 500 when entering weak password on signup page

### ISSUE THREAD

**Issue by alicoding** [mozilla/id.webmaker.org#205]
```
Debug: internal, implementation, error
    Error: Error: LoginAPI error
    at Object.exports.create (/Users/ali/projects/id.webmaker.org/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/Users/ali/projects/id.webmaker.org/node_modules/boom/lib/index.js:253:92)
    at Object.exports.badImplementation (/Users/ali/projects/id.webmaker.org/node_modules/boom/lib/index.js:289:23)
    at /Users/ali/projects/id.webmaker.org/web/server.js:267:31
    at /Users/ali/projects/id.webmaker.org/lib/account.js:134:11
    at IncomingMessage.<anonymous> (/Users/ali/projects/id.webmaker.org/lib/account.js:32:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

```

I'm getting error 500 when entering password that passes client-side but assuming that this failed server-side on Login requirement.

I entered `abc1234567` which is not acceptable, but `500` error is unpredictable :P

**Comment by alicoding** [comment]
cc @cadecairos
