### ISSUE TITLE
newrelic's trying to do things, despite use_newrelic=false

### ISSUE THREAD

**Issue by Pomax** [mozilla/id.webmaker.org#395]
My env is from the sample.env:
```
export NEW_RELIC_ENABLED=false
export NEW_RELIC_NO_CONFIG_FILE=true
```
however, npm start generates this error:
```
c:\Users\Pomax\Documents\Git\id.webmaker.org>npm start

> id.webmaker.org@1.0.0 start c:\Users\Pomax\Documents\Git\id.webmaker.org
> npm-run-all --parallel server watch:css watch:js


> id.webmaker.org@1.0.0 server c:\Users\Pomax\Documents\Git\id.webmaker.org
> node web/index.js


> id.webmaker.org@1.0.0 watch:css c:\Users\Pomax\Documents\Git\id.webmaker.org
> autoless --source-map templates/less public


> id.webmaker.org@1.0.0 watch:js c:\Users\Pomax\Documents\Git\id.webmaker.org
> npm run build:js -- --watch

c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\lib\config.js:227
  throw new Error(
  ^

Error: Unable to find New Relic module configuration. A default
configuration file can be copied from c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\lib\config.default.js
and put at c:\Users\Pomax\Documents\Git\id.webmaker.org\newrelic.js or
c:\Users\Pomax\Documents\Git\id.webmaker.org\web\newrelic.js.
    at _failHard (c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\lib\config.js:227:9)
    at Function.initialize (c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\lib\config.js:1050:25)
    at Object.<anonymous> (c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\lib\logger.js:18:37)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\Pomax\Documents\Git\id.webmaker.org\node_modules\newrelic\index.js:3:14)
```

(Windows 8.1, Node 4.4.1, npm 2.14)

**Comment by Pomax** [comment]
DISREGARD! I was running in the wrong id.wmo directory. Which has now been deleted >_>
